import { Geist, Geist_Mono, Manrope } from "next/font/google";
import "../globals.css";
import NavBar from "@/components/layouts/NavBar";
import Footer from "@/components/layouts/Footer";
import SmoothScroll from "@/components/UI/SmoothScroll";
import { Toaster } from "react-hot-toast";

const manRope = Manrope({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Penthusiasts",
  description: "Generated by Penthusiasts",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${manRope.className} antialiased`}>
        <NavBar />
        {children}
        <SmoothScroll />
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
