import { Manrope } from "next/font/google";
import "../globals.css";
import NavBar from "@/components/layouts/NavBar";
import Footer from "@/components/layouts/Footer";
import SmoothScroll from "@/components/UI/SmoothScroll";

const manRope = Manrope({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Penthusiasts",
  description: "Generated by Penthusiasts",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Add Calendly widget stylesheet globally */}
        <link
          href="https://assets.calendly.com/assets/external/widget.css"
          rel="stylesheet"
        />
      </head>
      <body className={`${manRope.className} antialiased relative`}>
        <NavBar />
        {children}
        <SmoothScroll />
        <Footer />
      </body>
    </html>
  );
}
